### ISSUE TITLE
Is there anyway to get a ttf file? 

### ISSUE THREAD

**Issue by nonetrix** [mutantstandard/build#5]
I would like this emoji set packaged in NixOS so I could use it system wide, I wasn't able to find a ttf option in the downloads page. There seems there used to be a way to do this based off this [AUR package build](url), but seems that the URL used will 404 now, also seems that the versioning system isn't ideal either for packaging upstream. I am really confused at this point, a script to just build the ttf would be ideal since NixOS is somewhat source based. There does seem to be some scripts to do at least something, but I think they are for rendering to PNG. This emoji set also has a lot of emojis that are as of now, technically out of spec would these be included like Nerd Fonts for example?

**Comment by nonetrix** [comment]
Package request
https://github.com/NixOS/nixpkgs/issues/312823

**Comment by dzuk-mutant** [comment]
I used to provide some experimental sbix-encoded emoji fonts, but I stopped because of the effort required to make a font versus the amount of people who would be able to use it didn't match up - https://blog.mutant.tech/index.php/2022/12/14/future-priorities/

I used to work on an experimental encoder for fonts that is designed to work fairly seamlessly with the project's emoji set compiler (Orxporter), but it is now a public archive. It only really reliably made semi-working sbix files. (I think if you wanted to compile an emoji font, Google now has a better open source solution.)

https://github.com/mutantstandard/forc

**Comment by nonetrix** [comment]
Closing for now then

**Comment by lavenderdotpet** [comment]
>https://blog.mutant.tech/index.php/2022/12/14/future-priorities/


this link is dead
